services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=postgres;Username=postgres;Password=helmirmili123
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://localhost:5000
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BASE_URL=http://localhost:5000
    depends_on:
      - backend

  db:
    image: postgres:17.4
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helmirmili123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

